name: netguru_task
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^6.1.3
  provider: ^4.3.3
  firebase_crashlytics: ^0.4.0+1
  intl: ^0.16.1
  flutter_secure_storage: ^3.3.5
  convex_bottom_bar: ^2.7.1+2
  shimmer: ^1.1.2
  lottie: ^0.7.0+1
  auto_size_text: ^2.1.0
  fluttertoast: ^7.1.6

  json_serializable: ^3.5.1
  equatable: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  mockito: ^4.1.4
  build_runner: ^1.10.11

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/lottie/
    - assets/json/values.json


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 700
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Caveat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Caveat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Caveat-Bold.ttf
          weight: 700


