name: netguru_task
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^6.1.3
  provider: ^4.3.3
  firebase_crashlytics: ^0.4.0+1
  intl: ^0.16.1
  flutter_secure_storage: ^3.3.5
  convex_bottom_bar: ^2.7.1+2

  json_serializable: ^3.5.1
  equatable: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  mockito: ^4.1.4
  build_runner: ^1.10.11

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/json/values.json


  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Thin.otf
          weight: 100
        - asset: assets/fonts/NotoSansJP-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansJP-Bold.otf
          weight: 600
        - asset: assets/fonts/NotoSansJP-Black.otf
          weight: 700
    - family: Catamaran
      fonts:
        - asset: assets/fonts/Catamaran-Thin.ttf
          weight: 100
        - asset: assets/fonts/Catamaran-Light.ttf
          weight: 300
        - asset: assets/fonts/Catamaran-Regular.ttf
          weight: 400
        - asset: assets/fonts/Catamaran-Medium.ttf
          weight: 500
        - asset: assets/fonts/Catamaran-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Catamaran-Bold.ttf
          weight: 700
        - asset: assets/fonts/Catamaran-ExtraBold.ttf
          weight: 800

